- name: cloud-data-discoverer.general
  rules:
  - alert: D8AzureCloudDataDiscovererCloudRequestError
    for: 1h
    expr: max by(job)(cloud_data_discovery_cloud_request_error == 1)
    labels:
      severity_level: "6"
      d8_module: cloud-provider-azure
      d8_component: cloud-data-discoverer
    annotations:
      plk_protocol_version: "1"
      plk_markup_format: "markdown"
      summary: Cloud data discoverer cannot get data from cloud
      plk_create_group_if_not_exists__malfunctioning: "D8AzureCloudDataDiscovererMalfunctioning,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
      plk_grouped_by__malfunctioning: "D8AzureCloudDataDiscovererMalfunctioning,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
      description: |
        Cloud data discoverer cannot get data from cloud. See cloud data discoverer logs for more information:
        `kubectl -n d8-cloud-provider-azure logs deploy/cloud-data-discoverer`

  - alert: D8AzureCloudDataDiscovererSaveError
    for: 1h
    expr: max by(job)(cloud_data_discovery_update_resource_error == 1)
    labels:
      severity_level: "6"
      d8_module: cloud-provider-azure
      d8_component: cloud-data-discoverer
    annotations:
      plk_protocol_version: "1"
      plk_markup_format: "markdown"
      summary: Cloud data discoverer cannot save data to k8s resource
      plk_create_group_if_not_exists__malfunctioning: "D8AzureCloudDataDiscovererMalfunctioning,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
      plk_grouped_by__malfunctioning: "D8AzureCloudDataDiscovererMalfunctioning,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
      description: |
        Cloud data discoverer cannot save data to k8s resource. See cloud data discoverer logs for more information:
        `kubectl -n d8-cloud-provider-azure logs deploy/cloud-data-discoverer`

